version: '3'
services:
  app:
    build: ./app
    container_name: app
    ports:
      - '80:80'
    env_file:
      - app/.env
    tty: true
    volumes:
      - ./app:/app
    networks:
      - backend
    depends_on:
      - db
  app_chat:
    build: ./app_chat
    container_name: app_chat
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - ./app_chat/serve.js:/app/serve.js
    networks:
      - backend
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: test_database
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - backend

  nginx:
    image: nginx
    ports:
      - "8080:80"

    volumes:
      - ./frontend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  backend:
    driver: bridge
