swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "melt"

host: "localhost:8080"

basePath: "/v2"

schemes:
  - "https"
  - "http"

paths:
  /contact:
    post:
      description: "Send contact."
      parameters:
        - name: a
          in: body
          schema:
            $ref: "#/definitions/SendContactRequest"
      responses:
        "200":
          description: OK
      tags:
        - Contact

definitions:
  SendContactRequest:
    title: SendContact
    type: object
    properties:
      address_list:
        type: array
        items: { type: integer }
      message:
        type: string
