openapi: 3.0.0
info:
  description: ""
  version: "1.0.0"
  title: "melt"

paths:
  /contact:
    post:
      description: "Send contact."
      requestBody:
        description: requests data
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendContactRequest"
      responses:
        '201':
          description: "Created"
      tags:
        - Contact

  /api/users/twitter_signin_url:
    get:
      description: twitter_signin_url
      operationId: signinUrRL
      responses:
        '200':
          description: user response
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    example: "https://api.twitter.com/oauth/authorize?oauth_token=xxxxxxx"
                  oauth_token:
                    type: string
                    example: "xxxxxxxxxx"
                  oauth_secret:
                    type: string
                    example: "zzzzzzzzzzz"

  /api/users/twitter_signup_url:
    get:
      description: twitter_signup_url
      operationId: signupUrRL
      responses:
        '200':
          description: user response
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    example: "https://api.twitter.com/oauth/authorize?oauth_token=xxxxxxx"
                  oauth_token:
                    type: string
                    example: "xxxxxxxxxx"
                  oauth_secret:
                    type: string
                    example: "zzzzzzzzzzz"

  /api/users/signup:
    post:
      description: signup
      operationId: signup
      requestBody:
        description: oauth tokens
        required: true
        content:
          application/json:
            schema:
                type: object
                properties:
                  oauth_token:
                    type: string
                    example: "hogehogehoeg"
                  oauth_secret:
                    type: string
                    example: "aaaaaaa.aaaaaaaaaaa"
                  oauth_verifier:
                    type: string
                    example: "aaaaaaa.aaaaaaaaaaa"
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'

  /api/users/signin:
    post:
      description: signin
      operationId: signin
      requestBody:
        description:  oauth tokens
        required: true
        content:
          application/json:
            schema:
                type: object
                properties:
                  oauth_token:
                    type: string
                    example: "hogehogehoeg"
                  oauth_secret:
                    type: string
                    example: "aaaaaaa.aaaaaaaaaaa"
                  oauth_verifier:
                    type: string
                    example: "aaaaaaa.aaaaaaaaaaa"
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: "object"
      required:
        - "name"
      properties:
        id:
          type: "integer"
          format: "int64"
          example: 100
        username:
          type: "string"
          example: "taro"
        display_name:
          type: "string"
          description: "displayname"
          example: "Taro★"
        icon_url:
          type: "string"
          description: "icon url"
          example: "http://example.com/icon.png"

    SendContactRequest:
      type: object
      description: SendContact
      properties:
        request_user_id_list:
          type: array
          items: { type: integer }
        message:
          type: string
