swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "melt"

host: "localhost:8080"

basePath: "/api"

schemes:
  - "http"

paths:
  /contact:
    post:
      description: "Send contact."
      parameters:
        - name: "request"
          in: body
          schema:
            $ref: "#/definitions/SendContactRequest"
      responses:
        "201":
          description: "Created"
      tags:
        - Contact
    get:
      description: "Get contact."
      parameters: []
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/GetContactResponse"
      tags:
        - Contact

definitions:
  SendContactRequest:
    title: SendContact
    type: object
    properties:
      request_user_id_list:
        type: array
        items: { type: integer }
      message:
        type: string
  GetContactResponse:
    title: GetContact
    type: object
    properties:
      received_contact_list:
        type: array
        items:
          $ref: "#/definitions/ContactItem"
      past_message_list:
        type: array
        items:
          $ref: "#/definitions/ContactItem"
  ContactItem:
    title: ContactItem
    type: object
    properties:
      send_user_id:
        type: integer
      message:
        type: string
      room_id:
        type: integer
      send_at:
        type: string
        format: date-time
